import type { Exercise } from "./types";

/**
 * Peak Pilates Level I exercise library.
 *
 * Tags drive contraindication matching — see contraindications.ts.
 */

export const MAT: Exercise[] = [
  {
    id: "mat-hundred",
    name: "Hundred",
    skill: "Introductory",
    reps: "100 pumps / 10 breaths",
    goal: "Promotes circulation, improves coordination with breath, centers mind/body",
    buildingBlocks: ["Feet on floor / knees bent", "Head down or supported"],
    variations: ["Power Circle between ankles or knees", "Breathe in fewer counts / exhale more"],
    tags: ["neck-loading", "deep-flexion", "hip-flexor-demand"],
  },
  {
    id: "mat-roll-up",
    name: "Roll Up",
    skill: "Introductory",
    reps: "5",
    goal: "Promotes spinal articulation, increases posterior flexibility",
    buildingBlocks: ["Bend knees, hold back of legs"],
    variations: ["Arms in line with ears", "Power Circle", "Light hand weights"],
    tags: ["deep-flexion", "hip-flexor-demand", "over-shoulder-height-arms"],
  },
  {
    id: "mat-one-leg-circle",
    name: "One Leg Circle",
    skill: "Introductory",
    reps: "5 each direction",
    goal: "Lengthens and tones thighs, stretches legs, teaches pelvic stabilization",
    buildingBlocks: ["Draw small capital D", "Bend knee for tight hamstrings"],
    variations: ["Open circle wider"],
    tags: ["light-hamstring-stretch", "hip-flexor-demand"],
  },
  {
    id: "mat-rolling-like-a-ball",
    name: "Rolling Like a Ball",
    skill: "Introductory",
    reps: "6–8",
    goal: "Promotes spinal massage, stimulates pressure points, promotes relaxation",
    buildingBlocks: ["Increase distance between heels and bottom", "Feet on floor"],
    variations: ["Power Circle between hands with straight arms", "Power Circle between knees"],
    tags: ["deep-flexion"],
  },
  {
    id: "mat-single-leg-stretch",
    name: "Abdominal Series: Single Leg Stretch",
    skill: "Introductory",
    series: "Abdominal Series",
    reps: "6–10",
    goal: "Strengthens and builds abdominal endurance, promotes alignment",
    buildingBlocks: ["Extend leg up higher", "Lie on back with knees bent, support head"],
    variations: [],
    tags: ["neck-loading"],
  },
  {
    id: "mat-double-leg-stretch",
    name: "Abdominal Series: Double Leg Stretch",
    skill: "Introductory",
    series: "Abdominal Series",
    reps: "6–10",
    goal: "Strengthens and builds abdominal endurance, teaches opposition",
    buildingBlocks: ["Extend both legs/arms to ceiling", "Hold back of thighs"],
    variations: ["Power Circle in hands or between ankles"],
    tags: ["neck-loading", "over-shoulder-height-arms"],
  },
  {
    id: "mat-single-straight-leg-stretch",
    name: "Abdominal Series: Single Straight Leg Stretch",
    skill: "Beginner",
    series: "Abdominal Series",
    reps: "6–10",
    goal: "Strengthens abdominal endurance, lengthens legs, stretches hamstrings",
    buildingBlocks: ["Reach and pull from behind thigh", "Hands under pelvis"],
    variations: [],
    tags: ["neck-loading", "light-hamstring-stretch"],
  },
  {
    id: "mat-double-straight-leg-lower-lift",
    name: "Abdominal Series: Double Straight Leg Lower Lift",
    skill: "Beginner",
    series: "Abdominal Series",
    reps: "6–10",
    goal: "Strengthens abdominal endurance, lengthens legs out of hips",
    buildingBlocks: ["Hands under pelvis", "Knees bent throughout"],
    variations: ["Power Circle between ankles"],
    tags: ["neck-loading", "hip-flexor-demand"],
  },
  {
    id: "mat-criss-cross",
    name: "Abdominal Series: Criss Cross",
    skill: "Beginner",
    series: "Abdominal Series",
    reps: "6–10",
    goal: "Strengthens abdominals (obliques), challenges rotation",
    buildingBlocks: ["Extend long leg to ceiling", "Feet on floor"],
    variations: ["Inhale 2 twists, exhale 2 twists"],
    tags: ["neck-loading", "rotation"],
  },
  {
    id: "mat-spine-stretch-forward",
    name: "Spine Stretch Forward",
    skill: "Introductory",
    reps: "5",
    goal: "Stretches lower lumbar and hamstrings, teaches sitting up out of hips",
    buildingBlocks: ["Bend knees and/or elevate hips", "Slide hands on floor"],
    variations: ["Arms overhead with bar or Power Circle", "Hold arches of feet"],
    tags: ["deep-flexion", "deep-hamstring-stretch"],
  },
  {
    id: "mat-open-leg-rocker-prep",
    name: "Open Leg Rocker–Prep",
    skill: "Beginner",
    reps: "Hold 10 seconds",
    goal: "Improves balance and control, prepares for full Open Leg Rocker",
    buildingBlocks: ["Keep one toe on floor", "Hold backs of thighs"],
    variations: ["Stretch both legs up at same time"],
    tags: ["hip-flexor-demand"],
  },
  {
    id: "mat-corkscrew-1",
    name: "Corkscrew I",
    skill: "Beginner",
    reps: "2–4 each direction",
    goal: "Strengthens Powerhouse, lengthens thighs, teaches leg-pelvis separation",
    buildingBlocks: ["Bend knees slightly", "Draw smaller circles", "Hands under pelvis"],
    variations: ["Change breath direction", "Power Circle between ankles"],
    tags: ["light-hamstring-stretch", "hip-flexor-demand"],
  },
  {
    id: "mat-saw",
    name: "Saw",
    skill: "Introductory",
    reps: "3–5 each direction",
    goal: "Stretches spine in rotation, strengthens abdominals, improves respiratory function",
    buildingBlocks: ["Bend knees slightly or elevate hips"],
    variations: ["1–3 lb arm weights"],
    tags: ["deep-flexion", "rotation", "deep-hamstring-stretch", "lateral-flexion"],
  },
  {
    id: "mat-swan-1-neck-roll",
    name: "Swan I–Neck Roll",
    skill: "Beginner",
    reps: "1–3",
    goal: "Stretches abdominals and neck, strengthens and lengthens spine in extension",
    buildingBlocks: ["Lift up just part of the way"],
    variations: ["Legs hip-width apart"],
    tags: ["extension", "prone", "light-wrist-loading"],
  },
  {
    id: "mat-shoulder-bridge-prep",
    name: "Shoulder Bridge–Prep",
    skill: "Beginner",
    reps: "3–5",
    goal: "Promotes Critical Connections activation, spinal articulation, neutral pelvis",
    buildingBlocks: ["Small range of motion", "Just perform Fundamental Clockwork"],
    variations: ["Power Circle or ball between knees", "Legs together firmly"],
    tags: ["extension"],
  },
  {
    id: "mat-side-kick-front-back",
    name: "Side Kick Series: Front and Back",
    skill: "Introductory",
    series: "Side Kick Series",
    reps: "5–10",
    goal: "Lengthens and tones thighs, hips, abdominals; teaches working legs from Powerhouse",
    buildingBlocks: ["Smaller range of motion", "Lay head on extended arm"],
    variations: ["Flex foot to front, point to back", "Light leg weights", "Hand behind head"],
    tags: ["light-hamstring-stretch", "light-wrist-loading", "over-shoulder-height-arms"],
  },
  {
    id: "mat-side-kick-up-down",
    name: "Side Kick Series: Up and Down",
    skill: "Introductory",
    series: "Side Kick Series",
    reps: "5",
    goal: "Lengthens and tones thighs, hips, abdominals; promotes balance",
    buildingBlocks: ["Lay head on extended arm", "Smaller range of motion"],
    variations: ["Flex foot up, point to lengthen down", "Hand behind head"],
    tags: ["light-wrist-loading", "over-shoulder-height-arms"],
  },
  {
    id: "mat-side-kick-circles",
    name: "Side Kick Series: Circles",
    skill: "Beginner",
    series: "Side Kick Series",
    reps: "5–8",
    goal: "Lengthens and tones thighs, hips, abdominals; promotes balance",
    buildingBlocks: ["Small range of motion, focus on Powerhouse"],
    variations: ["Power Circle with bottom leg inside", "Hand behind head"],
    tags: ["light-wrist-loading", "over-shoulder-height-arms"],
  },
  {
    id: "mat-side-kick-inner-thigh",
    name: "Side Kick Series: Inner Thigh Lifts and Circles",
    skill: "Introductory",
    series: "Side Kick Series",
    reps: "5–8",
    goal: "Lengthens and tones thighs and abdominals; stretches hips and buttocks",
    buildingBlocks: ["Top leg bent forward with knee to ceiling"],
    variations: ["Small or large circles", "Tempo changes", "Flex/point foot"],
    tags: ["light-wrist-loading", "over-shoulder-height-arms"],
  },
  {
    id: "mat-teaser-one-leg",
    name: "Teaser–One Leg",
    skill: "Beginner",
    reps: "3–4 per leg",
    goal: "Strengthens abdominals, promotes sequential articulation of spine",
    buildingBlocks: ["Place both feet on floor and hold back of thighs"],
    variations: ["Add twist toward bent leg", "Reach toward toes", "Hold bar or Power Circle"],
    tags: ["deep-flexion", "hip-flexor-demand", "over-shoulder-height-arms"],
  },
  {
    id: "mat-teaser-1",
    name: "Teaser I",
    skill: "Intermediate",
    reps: "3–5",
    goal: "Strengthens abdominals, improves sequential articulation of spine",
    buildingBlocks: ["Sit in V with knees bent, hold back of thighs"],
    variations: ["Power Circle between ankles", "Reach for toes on roll down", "Weighted bar"],
    tags: ["deep-flexion", "hip-flexor-demand", "over-shoulder-height-arms"],
  },
  {
    id: "mat-swimming-prep",
    name: "Swimming–Prep",
    skill: "Beginner",
    reps: "2–3 each side",
    goal: "Counter-stretch to Teaser; lengthens and strengthens spine in extension",
    buildingBlocks: ["Teach legs only", "Teach arms only"],
    variations: ["Switch arms/legs without touching mat", "Add head lift"],
    tags: ["extension", "prone", "over-shoulder-height-arms"],
  },
  {
    id: "mat-leg-pull-front-support",
    name: "Leg Pull Front–Support",
    skill: "Beginner",
    reps: "Hold 10 seconds",
    goal: "Strengthens and aligns upper body; strengthens Powerhouse",
    buildingBlocks: ["Bend knees to mat"],
    variations: [],
    tags: ["heavy-wrist-loading"],
  },
  {
    id: "mat-mermaid-stretch",
    name: "Mermaid Stretch",
    skill: "Beginner",
    reps: "2–3 each side",
    goal: "Stretches sides of spine, hips; opens ribcage; strengthens respiratory system",
    buildingBlocks: ["Open the knee angle as needed"],
    variations: ["Hold 1–2 lb weight", "Bend elbow at top", "Vary breathing"],
    tags: ["over-shoulder-height-arms"],
  },
  {
    id: "mat-beats-on-belly",
    name: "Beats on Belly",
    // Source table lists this as "Transition"; functions as Introductory for
    // program-generation purposes (instructor decision, 2026-07).
    skill: "Introductory",
    reps: "8–10 / 1–3 sets",
    goal: "Strengthens posterior muscles of spine and legs",
    buildingBlocks: ["Lie on stomach, lift through Powerhouse, no leg lifts"],
    variations: ["Change tempo"],
    tags: ["extension", "prone", "over-shoulder-height-arms"],
  },
  {
    id: "mat-seal",
    name: "Seal",
    skill: "Introductory",
    reps: "6–8",
    goal: "Promotes relaxation and massages spine as cool down",
    buildingBlocks: ["Hold position and clap feet without rolling", "Deepen C-curve"],
    variations: [],
    tags: ["deep-flexion"],
  },
  {
    id: "mat-push-up-series",
    name: "Push-Up Series",
    skill: "Intermediate",
    reps: "3–5 push-ups / 1–3 sets",
    goal: "Strengthens Powerhouse for torso support; strengthens upper body",
    buildingBlocks: ["Hold in Leg Pull Front–Support", "Push halfway", "Tabletop or bent knee"],
    variations: ["Push-ups on one leg", "Keep arms by ears on roll up"],
    tags: ["heavy-wrist-loading", "over-shoulder-height-arms", "deep-flexion", "deep-hamstring-stretch"],
  },
];

// V1 is Mat-only. Other apparatus live in future-apparatus.ts until V2.
export const LIBRARY: Exercise[] = [...MAT];

export const byId = new Map(LIBRARY.map((e) => [e.id, e]));
